---
version: "2"
services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Chicago}
    volumes:
      - wireshark-config:/config
    ports:
      - 3000:3000
    restart: unless-stopped
volumes:
  wireshark-config: